# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PageRechercheChapitreUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonAllerPageFeuilleAventure = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonAllerPageFeuilleAventure.setObjectName("ButtonAllerPageFeuilleAventure")
        self.verticalLayout.addWidget(self.ButtonAllerPageFeuilleAventure)
        self.labelInstructionPage = QtWidgets.QLabel(self.centralwidget)
        self.labelInstructionPage.setEnabled(True)
        self.labelInstructionPage.setMaximumSize(QtCore.QSize(780, 256))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelInstructionPage.setFont(font)
        self.labelInstructionPage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelInstructionPage.setAutoFillBackground(False)
        self.labelInstructionPage.setTextFormat(QtCore.Qt.AutoText)
        self.labelInstructionPage.setScaledContents(False)
        self.labelInstructionPage.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelInstructionPage.setIndent(-1)
        self.labelInstructionPage.setObjectName("labelInstructionPage")
        self.verticalLayout.addWidget(self.labelInstructionPage)
        self.lineEditChapitreVoulu = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditChapitreVoulu.setObjectName("lineEditChapitreVoulu")
        self.verticalLayout.addWidget(self.lineEditChapitreVoulu)
        self.ButtonChangerChapitre = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonChangerChapitre.setObjectName("ButtonChangerChapitre")
        self.verticalLayout.addWidget(self.ButtonChangerChapitre)
        self.labelChapitre = QtWidgets.QLabel(self.centralwidget)
        self.labelChapitre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelChapitre.setObjectName("labelChapitre")
        self.verticalLayout.addWidget(self.labelChapitre)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButtonAllerPageFeuilleAventure.setText(_translate("MainWindow", "Feuille Aventure"))
        self.labelInstructionPage.setText(_translate("MainWindow", "Veuillez sélectionner la page voulue"))
        self.ButtonChangerChapitre.setText(_translate("MainWindow", "Rechercher"))
        self.labelChapitre.setText(_translate("MainWindow", "TextLabel"))
