# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectionLivre.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelLivreChoix = QtWidgets.QLabel(self.centralwidget)
        self.labelLivreChoix.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLivreChoix.setObjectName("labelLivreChoix")
        self.verticalLayout.addWidget(self.labelLivreChoix)
        self.comboBoxLivreDisponible = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxLivreDisponible.setObjectName("comboBoxLivreDisponible")
        self.verticalLayout.addWidget(self.comboBoxLivreDisponible)
        self.ButtonValiderLivre = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonValiderLivre.setObjectName("ButtonValiderLivre")
        self.verticalLayout.addWidget(self.ButtonValiderLivre)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelLivreChoix.setText(_translate("MainWindow", "Veuillez choisir le livre voulue"))
        self.ButtonValiderLivre.setText(_translate("MainWindow", "ButtonValiderLivre"))
